services:
  app:
    build:
      context: .
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
    command: ["node", ".output/server/index.mjs"]
